run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - deadcode
    - structcheck
    - unconvert
    - prealloc
    - staticcheck
  disable:
    - lll